version: '3'
services:
  listener:
    image: ants1  
    container_name: listener
    networks:
      my_custom_bridge:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    expose:
      - "1-60000"
   
  scanner:
    image: my_nmap  
    container_name: scanner
    networks:
      my_custom_bridge:
    stdin_open: true
    tty: true
    command: ["sleep", "infinity"]  
    cap_add:
      - NET_ADMIN
      - NET_RAW
    expose:
      - "1-60000"
networks:
  my_custom_bridge:
    external: true
