version: '3'
services:
  listener:
    image: ants1  
    container_name: listener
    networks:
      my_custom_bridge:
        ipv4_address: 172.19.0.2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    expose:
      - "0"  

  scanner:
    image: my_nmap  
    container_name: scanner
    networks:
      my_custom_bridge:
    stdin_open: true
    tty: true
    command: ["sleep", "infinity"]  
    cap_add:
      - NET_ADMIN
      - NET_RAW
    expose:
      - "0"  

networks:
  my_custom_bridge:
    external: true
